providers = ["php"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --ignore-platform-reqs"
]

[start]
cmd = "php artisan migrate --force || true && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
